### ISSUE TITLE
Self discovery of annoted workers finds and runs workers from Examples folder

### ISSUE THREAD

**Issue by petersladek** [conductor-sdk/conductor-csharp#121]
If I use WorkflowTaskHost.CreateWorkerHost() in my own worker project the self discovery of annoted workers (those using attribute [WorkerTask]) finds and runs workers from Examples folder placed directly in sdk project. It would be best to move the whole Examples folder to existing csharp-examples project, it doesn't make sense to be placed in core sdk library. Thank you.

**Comment by SitamMatt** [comment]
I also encountered this problem. My job worker broke after updating to 1.0.15.
