### ISSUE TITLE
Improve TaskRunner polling strategy

### ISSUE THREAD

**Issue by gardusig** [conductor-sdk/conductor-csharp#14]

**Comment by superff** [comment]
Could the c# client add the paused property to the worker as the Java client? and only poll the task if the paused flag is false

https://orkes.io/content/docs/how-tos/Workers/build-a-java-task-worker

**Comment by gardusig** [comment]
Done by: https://github.com/conductor-sdk/conductor-csharp/releases/tag/1.0.0
