### ISSUE TITLE
Conductor.Client.ApiException: Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by Taqi-Techverx** [conductor-sdk/conductor-csharp#40]
![image](https://user-images.githubusercontent.com/37609524/207903680-b1b08a04-553a-4ef4-9825-b783ad0aa230.png)

@manan164 can you please look into this?

I'm using the latest conductor-csharp version 0.1.1

**Comment by manan164** [comment]
Hi @Taqi-Techverx , Generally this happens when basePath is given wrong. Have you suffixed `/api` in basePath?

**Comment by Taqi-Techverx** [comment]
<img width="467" alt="Screenshot 2022-12-15 204819" src="https://user-images.githubusercontent.com/37609524/207905537-0ea34eaf-a3f7-45dc-ad32-9f5e5137eeb6.png">
@manan164

**Comment by Taqi-Techverx** [comment]
You mean base path should be this https://play.orkes.io/api ?
