### ISSUE TITLE
Async / Non blocking support

### ISSUE THREAD

**Issue by ZergRushJoe** [conductor-sdk/conductor-csharp#86]
I would like some interfaces to support tasks/async methods. Right now the main thread is blocked by any network call. This is a problem for using the api client. Workers can also be made async as well for pull loop would allow a cancelation token to be used so the worker can exit gracefully.

The Microsoft docs they use the async methods to avoid threading issues.
 https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-7.0&tabs=visual-studio

**Comment by mmccord-processunity** [comment]
@ZergRushJoe -- I had the same thought. It [appears here](https://github.com/conductor-sdk/conductor-csharp/commit/7cd56e8e6120630d89e56761a202a66b7657338f#r134382583) that it was at one point async and then changed to synchronous. I assume there was some advantage to doing this, but I'm not seeing it. I asked @gardusig (the author of the commit for comment). Additionally the documentation still indicates async [as here](https://conductor.netflix.com/documentation/clientsdks/csharp-sdk.html#write-workers) even though per @gardusig's change, it is now synchronous.

**Comment by gardusig** [comment]
Quick explanation about overall architecture.

- there's a [WorkflowTaskCoordinator](https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/Worker/WorkflowTaskCoordinator.cs) responsible for all workers
- each worker is a [WorkflowTaskExecutor](https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/Worker/WorkflowTaskExecutor.cs)
- specifically, they each have an infinite independent loop [here](https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/Worker/WorkflowTaskExecutor.cs#L60-L79)
- you can see that it polls for a list of tasks and starts a new thread for each [here](https://github.com/conductor-sdk/conductor-csharp/blob/main/Conductor/Client/Worker/WorkflowTaskExecutor.cs#L119-L130)

It was the first time I coded in C#, so I'm not that familiar with its multithreading handling. If the async issue is blocking multiple I/O operations at the same time. I think the code change to make that improvement might be quite short.

**Comment by gardusig** [comment]
Maybe it's as simple as adding an async before each method declaration and then making the right call at their infinite loop.

```csharp
private async void Work4Ever()
```

Then play around with their [main startup method](https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/Worker/WorkflowTaskCoordinator.cs#L27)

**Comment by mmccord-processunity** [comment]
Gotcha. Thanks for the info and the prompt reply!

**Comment by ZergRushJoe** [comment]
Yes can also use task.waitall as a way to run all the batched task at the same time but still wait for all to finsh before getting the next batch.
