### ISSUE TITLE
Rename the Task Class 

### ISSUE THREAD

**Issue by j0nimost** [conductor-sdk/conductor-csharp#90]
I have come across a conflict between `System.Threads.Tasks.Task` and `Conductor.Client.Models.Task` The class in question is here: https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/Models/Task.cs#L12-L18

Can it be renamed to something else?

**Comment by v1r3n** [comment]
Hi @j0nimost we will consider this in the future versions, currently changing the name is going to cause backwards compatibility issues.  Closing this issue for now, but we will certainly find a way in the future releases.
