### ISSUE TITLE
The ApiClient does allow for custom serialization

### ISSUE THREAD

**Issue by zacrumford** [conductor-sdk/conductor-csharp#93]
See [this](https://github.com/conductor-sdk/conductor-csharp/blob/ec6a079113826782d26c83b6b5b6d037860cfc9c/Conductor/Client/ApiClient.cs#L295C61-L295C61) line for details.

There is no way to supply a custom serializer in ApiClient. While there exists the 'serializerSettings' member, there are two issues with this:
1. this is not use as input to JsonConvert.Serialize() during serialization
2. the `serializerSettings` member is private and there is no way of setting it in a constructor.

Additionally, one would think that `ApiClient.RestClient.UseSerializer<T>` (or the Newtonsoft extension `UseNewtonsoftJson`) would have an effect but this is completely unused in ApiClient.

Proposed fixes:
1. Add a ctor to allow overload for serialization settings and use that.
2. Use the serializer in the RestClient

Note: callers *can* work around this by configuring newtonsoft's default serializer options but this is error prone and affects the whole process.

**Comment by amid0** [comment]
Also faced with serialization issue.
In a project used System.Text.Json serialization 
And after calling start workflow API 
Got this instead of string values )

![image](https://github.com/conductor-sdk/conductor-csharp/assets/6542910/631bb5d1-0aff-46c5-af40-e0d780511009)
