### ISSUE TITLE
No SDK support for the Update Workflow Variables Endpoint?

### ISSUE THREAD

**Issue by mross002** [conductor-sdk/conductor-csharp#95]
There appears to be an endpoint to update Workflow variables on the Swagger API page, but it's not (from what we could find) supported in the SDK, we had to add a separate method in our project to call the API directly via HttpClient rather than using the SDK.  Can this be added to the SDK please?  Thanks!

<img width="1525" alt="image" src="https://github.com/conductor-sdk/conductor-csharp/assets/794345/c31b63b8-cea1-4dad-8c18-1d68838a2f58">

**Comment by v1r3n** [comment]
Hi @mross002 the new version expected to be available soon should have this.  stay tuned!

**Comment by v1r3n** [comment]
Hi @mross002 this API is now available in the latest version that was released.

**Comment by v1r3n** [comment]
Hi @mross002 closing this as this was already released.  Please feel free to open the issue again if you need further help.
